### ISSUE TITLE
Make filed

### ISSUE THREAD

**Issue by JunnamLee** [ARUP-NGS/BMFtools#94]
Hi. Daniel

I have some problem when I typing make command.

#make
cd dlib && git checkout v0.3 && cd ..
HEAD is now at f90ae8b... Add zr2
g++ -Wuninitialized -Wunreachable-code -Wall -fopenmp -DBMF_VERSION=\"v1.1-3-gb40d\" -std=c++11 -fno-builtin-gamma -pedantic   -Ihtslib -Iinclude -I.  -lm -lz -lpthread -Wno-unused-result -finline-functions -O3 -DNDEBUG -flto -fivopts -Wno-unused-function -Wno-strict-aliasing -fno-builtin-gamma include/sam_opts.o src/bmf_collapse.o include/igamc_cephes.o lib/hashdmp.o src/bmf_rsq.o src/bmf_famstats.o include/bedidx.o src/bmf_err.o lib/kingfisher.o src/bmf_mark.o src/bmf_cap.o lib/mseq.o lib/splitter.o src/bmf_main.o src/bmf_target.o src/bmf_depth.o src/bmf_vet.o src/bmf_sort.o src/bmf_stack.o lib/stack.o src/bmf_filter.o dlib/cstr_util.o dlib/math_util.o dlib/vcf_util.o dlib/io_util.o dlib/bam_util.o dlib/nix_util.o dlib/bed_util.o dlib/misc_util.o libhts.a -o bmftools
src/bmf_collapse.o (symbol from plugin): warning: memset used with constant zero length parameter; this could be due to transposed parameters
/tmp/ccI06CdG.ltrans0.ltrans.o: In function `bmf::hash_inmem_inline_core(char*, char*, char*, char*, char*, int, int, int, int, int)':
<artificial>:(.text+0x162): undefined reference to `gzdopen'
<artificial>:(.text+0x186): undefined reference to `gzdopen'
<artificial>:(.text+0x41d): undefined reference to `gzclose'
<artificial>:(.text+0x42a): undefined reference to `gzclose'
<artificial>:(.text+0xfe6): undefined reference to `gzputs'
<artificial>:(.text+0x1004): undefined reference to `gzputs'
<artificial>:(.text+0x3964): undefined reference to `gzputs'
<artificial>:(.text+0x39bb): undefined reference to `gzputs'
<artificial>:(.text+0x3ab5): undefined reference to `gzclose'
<artificial>:(.text+0x3abf): undefined reference to `gzclose'
<artificial>:(.text+0x3f80): undefined reference to `gzclose'
<artificial>:(.text+0x4057): undefined reference to `gzclose'
/tmp/ccI06CdG.ltrans2.ltrans.o: In function `bmf::stranded_hash_dmp_core(char*, char*, int)':
<artificial>:(.text+0x6a): undefined reference to `gzopen'
<artificial>:(.text+0x8e): undefined reference to `gzopen'
<artificial>:(.text+0x1ec2): undefined reference to `gzputs'
<artificial>:(.text+0x2084): undefined reference to `gzputs'
<artificial>:(.text+0x20df): undefined reference to `gzclose'
<artificial>:(.text+0x20e9): undefined reference to `gzclose'
<artificial>:(.text+0x2939): undefined reference to `gzclose'
<artificial>:(.text+0x2943): undefined reference to `gzclose'
/tmp/ccI06CdG.ltrans3.ltrans.o: In function `bmf::depth_main(int, char**)':
<artificial>:(.text+0x3d4): undefined reference to `gzopen'
<artificial>:(.text+0x603): undefined reference to `gzread'
<artificial>:(.text+0x105a): undefined reference to `gzclose'
/tmp/ccI06CdG.ltrans4.ltrans.o: In function `kseq_read(kseq_t*) [clone .lto_priv.249]':
<artificial>:(.text+0x498): undefined reference to `gzread'
<artificial>:(.text+0x519): undefined reference to `gzread'
<artificial>:(.text+0x6cd): undefined reference to `gzread'
<artificial>:(.text+0x896): undefined reference to `gzread'
<artificial>:(.text+0x8e4): undefined reference to `gzread'
/tmp/ccI06CdG.ltrans4.ltrans.o: In function `bmf::idmp_main(int, char**)':
<artificial>:(.text+0x1bed): undefined reference to `gzopen'
<artificial>:(.text+0x1ede): undefined reference to `gzprintf'
<artificial>:(.text+0x2083): undefined reference to `gzprintf'
<artificial>:(.text+0x20d4): undefined reference to `gzclose'
<artificial>:(.text+0x2103): undefined reference to `gzclose'
<artificial>:(.text+0x2459): undefined reference to `gzopen'
<artificial>:(.text+0x2473): undefined reference to `gzopen'
<artificial>:(.text+0x2782): undefined reference to `gzprintf'
<artificial>:(.text+0x27c9): undefined reference to `gzprintf'
<artificial>:(.text+0x2bff): undefined reference to `gzprintf'
<artificial>:(.text+0x2c34): undefined reference to `gzprintf'
<artificial>:(.text+0x2c7c): undefined reference to `gzclose'
<artificial>:(.text+0x2c91): undefined reference to `gzclose'
<artificial>:(.text+0x2cd1): undefined reference to `gzclose'
<artificial>:(.text+0x2cdb): undefined reference to `gzclose'
<artificial>:(.text+0x2e2f): undefined reference to `gzprintf'
<artificial>:(.text+0x2e62): undefined reference to `gzprintf'
<artificial>:(.text+0x2f47): undefined reference to `gzprintf'
/tmp/ccI06CdG.ltrans11.ltrans.o: In function `bmf::init_splitter(bmf::marksplit_settings_t*)':
<artificial>:(.text+0x1ef): undefined reference to `gzopen'
<artificial>:(.text+0x205): undefined reference to `gzopen'
<artificial>:(.text+0x336): undefined reference to `gzopen'
/tmp/ccI06CdG.ltrans12.ltrans.o: In function `kseq_read(kseq_t*) [clone .lto_priv.240]':
<artificial>:(.text+0x518): undefined reference to `gzread'
<artificial>:(.text+0x599): undefined reference to `gzread'
<artificial>:(.text+0x74d): undefined reference to `gzread'
<artificial>:(.text+0x916): undefined reference to `gzread'
<artificial>:(.text+0x964): undefined reference to `gzread'
/tmp/ccI06CdG.ltrans12.ltrans.o: In function `bmf::sdmp_main(int, char**) [clone .part.14] [clone .lto_priv.257]':
<artificial>:(.text+0x1edd): undefined reference to `gzopen'
<artificial>:(.text+0x1ef7): undefined reference to `gzopen'
<artificial>:(.text+0x1f45): undefined reference to `gzopen'
<artificial>:(.text+0x2168): undefined reference to `gzprintf'
<artificial>:(.text+0x21b0): undefined reference to `gzprintf'
<artificial>:(.text+0x220c): undefined reference to `gzclose'
<artificial>:(.text+0x2216): undefined reference to `gzclose'
<artificial>:(.text+0x2220): undefined reference to `gzclose'
<artificial>:(.text+0x2242): undefined reference to `gzclose'
<artificial>:(.text+0x2252): undefined reference to `gzclose'
<artificial>:(.text+0x2405): undefined reference to `gzopen'
<artificial>:(.text+0x241f): undefined reference to `gzopen'
<artificial>:(.text+0x28a1): undefined reference to `gzprintf'
<artificial>:(.text+0x28d1): undefined reference to `gzprintf'
<artificial>:(.text+0x2946): undefined reference to `gzprintf'
<artificial>:(.text+0x2ac8): undefined reference to `gzprintf'
<artificial>:(.text+0x2afe): undefined reference to `gzclose'
<artificial>:(.text+0x2b08): undefined reference to `gzclose'
<artificial>:(.text+0x2b23): undefined reference to `gzclose'
/tmp/ccI06CdG.ltrans14.ltrans.o: In function `dlib::open_gzfile(char*, char const*)':
<artificial>:(.text+0x1993): undefined reference to `gzdopen'
<artificial>:(.text+0x19a1): undefined reference to `gzopen'
/tmp/ccI06CdG.ltrans15.ltrans.o: In function `bmf::hash_dmp_core(char*, char*, int)':
<artificial>:(.text+0x97): undefined reference to `gzopen'
<artificial>:(.text+0xb9): undefined reference to `gzdopen'
<artificial>:(.text+0x1864): undefined reference to `gzputs'
<artificial>:(.text+0x1c31): undefined reference to `gzclose'
<artificial>:(.text+0x1c3b): undefined reference to `gzclose'
<artificial>:(.text+0x1d9e): undefined reference to `gzclose'
<artificial>:(.text+0x1dba): undefined reference to `gzclose'
<artificial>:(.text+0x1dcc): undefined reference to `gzclose'
/tmp/ccI06CdG.ltrans16.ltrans.o: In function `ks_getuntil2(__kstream_t*, int, __kstring_t*, int*, int) [clone .constprop.80]':
<artificial>:(.text+0x114): undefined reference to `gzread'
/tmp/ccI06CdG.ltrans16.ltrans.o: In function `ks_getuntil2(__kstream_t*, int, __kstring_t*, int*, int) [clone .constprop.68]':
<artificial>:(.text+0x924): undefined reference to `gzread'
/tmp/ccI06CdG.ltrans22.ltrans.o: In function `dlib::parse_bed_hash(char const*, bam_hdr_t*, unsigned int)':
<artificial>:(.text+0x351): undefined reference to `gzopen'
<artificial>:(.text+0x38e): undefined reference to `gzgets'
<artificial>:(.text+0x51a): undefined reference to `gzclose'
libhts.a(hts.o): In function `decompress_peek':
/BiO/BioTools/BMFtools/htslib/hts.c:142: undefined reference to `inflateInit2_'
/BiO/BioTools/BMFtools/htslib/hts.c:145: undefined reference to `inflate'
/BiO/BioTools/BMFtools/htslib/hts.c:148: undefined reference to `inflateEnd'
/BiO/BioTools/BMFtools/htslib/hts.c:148: undefined reference to `inflateEnd'
libhts.a(vcf.o): In function `vcf_hdr_read':
/BiO/BioTools/BMFtools/htslib/vcf.c:1288: undefined reference to `gzopen'
libhts.a(vcf.o): In function `ks_getc':
/BiO/BioTools/BMFtools/htslib/vcf.c:49: undefined reference to `gzread'
libhts.a(vcf.o): In function `vcf_hdr_read':
/BiO/BioTools/BMFtools/htslib/vcf.c:1301: undefined reference to `gzclose'
libhts.a(cram_io.o): In function `zlib_mem_deflate':
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:782: undefined reference to `deflateInit2_'
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:796: undefined reference to `deflate'
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:803: undefined reference to `deflate'
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:808: undefined reference to `deflateEnd'
libhts.a(cram_io.o): In function `itf8_decode_crc':
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:216: undefined reference to `crc32'
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:225: undefined reference to `crc32'
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:201: undefined reference to `crc32'
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:208: undefined reference to `crc32'
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:195: undefined reference to `crc32'
libhts.a(cram_io.o):/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:600: more undefined references to `crc32' follow
libhts.a(cram_io.o): In function `zlib_mem_inflate':
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:718: undefined reference to `inflateInit2_'
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:731: undefined reference to `inflate'
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:751: undefined reference to `inflateEnd'
libhts.a(cram_io.o): In function `cram_read_block':
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:946: undefined reference to `crc32'
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:948: undefined reference to `crc32'
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:980: undefined reference to `crc32'
libhts.a(cram_io.o): In function `cram_write_block':
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:1049: undefined reference to `crc32'
/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:1054: undefined reference to `crc32'
libhts.a(cram_io.o):/BiO/BioTools/BMFtools/htslib/cram/cram_io.c:3092: more undefined references to `crc32' follow
libhts.a(zfio.o): In function `zfputs':
/BiO/BioTools/BMFtools/htslib/cram/zfio.c:80: undefined reference to `gzputs'
libhts.a(zfio.o): In function `zfpeek':
/BiO/BioTools/BMFtools/htslib/cram/zfio.c:97: undefined reference to `gzungetc'
/BiO/BioTools/BMFtools/htslib/cram/zfio.c:95: undefined reference to `gzgetc'
libhts.a(zfio.o): In function `zfopen':
/BiO/BioTools/BMFtools/htslib/cram/zfio.c:165: undefined reference to `gzopen'
/BiO/BioTools/BMFtools/htslib/cram/zfio.c:169: undefined reference to `gzopen'
libhts.a(zfio.o): In function `zfclose':
/BiO/BioTools/BMFtools/htslib/cram/zfio.c:180: undefined reference to `gzclose'
libhts.a(zfio.o): In function `zfgets':
/BiO/BioTools/BMFtools/htslib/cram/zfio.c:69: undefined reference to `gzgets'
libhts.a(zfio.o): In function `zfeof':
/BiO/BioTools/BMFtools/htslib/cram/zfio.c:105: undefined reference to `gzeof'
libhts.a(bgzf.o): In function `bgzf_write_init':
/BiO/BioTools/BMFtools/htslib/bgzf.c:166: undefined reference to `deflateInit2_'
libhts.a(bgzf.o): In function `inflate_gzip_block':
/BiO/BioTools/BMFtools/htslib/bgzf.c:335: undefined reference to `inflate'
libhts.a(bgzf.o): In function `bgzf_open':
/BiO/BioTools/BMFtools/htslib/bgzf.c:174: undefined reference to `compressBound'
libhts.a(bgzf.o): In function `bgzf_dopen':
/BiO/BioTools/BMFtools/htslib/bgzf.c:196: undefined reference to `compressBound'
libhts.a(bgzf.o): In function `bgzf_hopen':
/BiO/BioTools/BMFtools/htslib/bgzf.c:218: undefined reference to `compressBound'
libhts.a(bgzf.o): In function `bgzf_compress':
/BiO/BioTools/BMFtools/htslib/bgzf.c:244: undefined reference to `deflateInit2_'
/BiO/BioTools/BMFtools/htslib/bgzf.c:245: undefined reference to `deflate'
/BiO/BioTools/BMFtools/htslib/bgzf.c:246: undefined reference to `deflateEnd'
/BiO/BioTools/BMFtools/htslib/bgzf.c:252: undefined reference to `crc32'
/BiO/BioTools/BMFtools/htslib/bgzf.c:252: undefined reference to `crc32'
libhts.a(bgzf.o): In function `bgzf_gzip_compress':
/BiO/BioTools/BMFtools/htslib/bgzf.c:267: undefined reference to `deflate'
libhts.a(bgzf.o): In function `bgzf_read_block':
/BiO/BioTools/BMFtools/htslib/bgzf.c:505: undefined reference to `inflateInit2_'
libhts.a(bgzf.o): In function `inflate_block':
/BiO/BioTools/BMFtools/htslib/bgzf.c:302: undefined reference to `inflateInit2_'
/BiO/BioTools/BMFtools/htslib/bgzf.c:306: undefined reference to `inflate'
/BiO/BioTools/BMFtools/htslib/bgzf.c:311: undefined reference to `inflateEnd'
/BiO/BioTools/BMFtools/htslib/bgzf.c:307: undefined reference to `inflateEnd'
libhts.a(bgzf.o): In function `bgzf_close':
/BiO/BioTools/BMFtools/htslib/bgzf.c:816: undefined reference to `inflateEnd'
/BiO/BioTools/BMFtools/htslib/bgzf.c:817: undefined reference to `deflateEnd'
/BiO/BioTools/BMFtools/htslib/bgzf.c:817: undefined reference to `deflateEnd'
collect2: error: ld returned 1 exit status
make: *** [test/ucs/ucs_test] Error 1

This is my environments
ubuntu : 
root@greencross:/BiO/BioTools/BMFtools# uname -a
Linux greencross 3.16.0-031600-generic #201408031935 SMP Sun Aug 3 23:36:11 UTC 2014 x86_64 x86_64 x86_64  #GNU/Linux

gcc : 4.9.3

I try to fix it with previous discuss

but can not find the solution.

In Makefiles, the LIB variable has empty path, Is this correct script? 

After writing above issues, the tool are appeared at the dir. 

I try to the tool and notify you the any bugs and questions 

Thanks.

**Comment by madsheilskov** [comment]
I just posted a similar issue under '#93 make failed'.

**Comment by dnbh** [comment]
Have your issues been resolved by using the fork?

**Comment by dnbh** [comment]
I've been in communication with you, and I think it was resolved. Is this issue ready to be closed?

**Comment by JunnamLee** [comment]
Dear Daniel,

I am sorry for late reply.

Yeap. I think the issues were solved

Thanks.

Jun

2017-02-22 19:42 GMT-08:00 Daniel Baker <notifications@github.com>:

**Comment by dnbh** [comment]
@BrettKennedy I believe this and [this](https://github.com/ARUP-NGS/BMFtools/issues/93) are ready to be closed.
